// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {scanner} from '../models';

export function CleanCategories(arg1:Array<string>):Promise<scanner.CleanResult>;

export function CleanPaths(arg1:Array<string>):Promise<scanner.CleanResult>;

export function DebugScanFolder(arg1:string):Promise<Record<string, any>>;

export function ExportScanToJSON():Promise<string>;

export function FormatSize(arg1:number):Promise<string>;

export function GetCategoryItems(arg1:string):Promise<Array<scanner.FileNode>>;

export function GetDevCategories():Promise<Array<scanner.Category>>;

export function GetDirectoryChildren(arg1:string):Promise<Array<scanner.FileNode>>;

export function GetHomeDir():Promise<string>;

export function QuickScanDev():Promise<scanner.ScanResult>;

export function ScanCategory(arg1:string):Promise<scanner.Category>;

export function ScanDev():Promise<scanner.ScanResult>;

export function ScanNormal():Promise<scanner.FullScanResult>;

export function ScanNormalPath(arg1:string):Promise<scanner.FullScanResult>;
