// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CleanCategories(arg1) {
  return window['go']['main']['App']['CleanCategories'](arg1);
}

export function CleanPaths(arg1) {
  return window['go']['main']['App']['CleanPaths'](arg1);
}

export function FormatSize(arg1) {
  return window['go']['main']['App']['FormatSize'](arg1);
}

export function GetCategoryItems(arg1) {
  return window['go']['main']['App']['GetCategoryItems'](arg1);
}

export function GetDevCategories() {
  return window['go']['main']['App']['GetDevCategories']();
}

export function GetDirectoryChildren(arg1) {
  return window['go']['main']['App']['GetDirectoryChildren'](arg1);
}

export function GetHomeDir() {
  return window['go']['main']['App']['GetHomeDir']();
}

export function QuickScanDev() {
  return window['go']['main']['App']['QuickScanDev']();
}

export function ScanCategory(arg1) {
  return window['go']['main']['App']['ScanCategory'](arg1);
}

export function ScanDev() {
  return window['go']['main']['App']['ScanDev']();
}

export function ScanNormal() {
  return window['go']['main']['App']['ScanNormal']();
}

export function ScanNormalPath(arg1) {
  return window['go']['main']['App']['ScanNormalPath'](arg1);
}
