// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CancelClean() {
  return window['go']['main']['App']['CancelClean']();
}

export function CancelScan() {
  return window['go']['main']['App']['CancelScan']();
}

export function CleanCategories(arg1) {
  return window['go']['main']['App']['CleanCategories'](arg1);
}

export function ClearCache() {
  return window['go']['main']['App']['ClearCache']();
}

export function ClearTrendsHistory() {
  return window['go']['main']['App']['ClearTrendsHistory']();
}

export function DeleteDuplicateGroup(arg1) {
  return window['go']['main']['App']['DeleteDuplicateGroup'](arg1);
}

export function DeleteNodeModules(arg1) {
  return window['go']['main']['App']['DeleteNodeModules'](arg1);
}

export function DeletePath(arg1, arg2) {
  return window['go']['main']['App']['DeletePath'](arg1, arg2);
}

export function DeletePaths(arg1, arg2) {
  return window['go']['main']['App']['DeletePaths'](arg1, arg2);
}

export function FindDuplicates() {
  return window['go']['main']['App']['FindDuplicates']();
}

export function FindDuplicatesInPath(arg1, arg2) {
  return window['go']['main']['App']['FindDuplicatesInPath'](arg1, arg2);
}

export function FindLargeFiles(arg1) {
  return window['go']['main']['App']['FindLargeFiles'](arg1);
}

export function FindLargeFilesWithOptions(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['FindLargeFilesWithOptions'](arg1, arg2, arg3, arg4);
}

export function FormatSize(arg1) {
  return window['go']['main']['App']['FormatSize'](arg1);
}

export function GetCacheInfo() {
  return window['go']['main']['App']['GetCacheInfo']();
}

export function GetCategoryItems(arg1) {
  return window['go']['main']['App']['GetCategoryItems'](arg1);
}

export function GetDevCategories() {
  return window['go']['main']['App']['GetDevCategories']();
}

export function GetDirectoryChildren(arg1) {
  return window['go']['main']['App']['GetDirectoryChildren'](arg1);
}

export function GetDiskTrends() {
  return window['go']['main']['App']['GetDiskTrends']();
}

export function GetGrowthAlerts(arg1) {
  return window['go']['main']['App']['GetGrowthAlerts'](arg1);
}

export function GetHomeDir() {
  return window['go']['main']['App']['GetHomeDir']();
}

export function GetPermanentDelete() {
  return window['go']['main']['App']['GetPermanentDelete']();
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function IsCategoryEnabled(arg1) {
  return window['go']['main']['App']['IsCategoryEnabled'](arg1);
}

export function LoadCachedDevScan() {
  return window['go']['main']['App']['LoadCachedDevScan']();
}

export function LoadCachedNormalScan() {
  return window['go']['main']['App']['LoadCachedNormalScan']();
}

export function QuickScanDev() {
  return window['go']['main']['App']['QuickScanDev']();
}

export function RecordDiskSnapshot(arg1) {
  return window['go']['main']['App']['RecordDiskSnapshot'](arg1);
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}

export function ScanCategory(arg1) {
  return window['go']['main']['App']['ScanCategory'](arg1);
}

export function ScanDev() {
  return window['go']['main']['App']['ScanDev']();
}

export function ScanNodeModules() {
  return window['go']['main']['App']['ScanNodeModules']();
}

export function ScanNormal() {
  return window['go']['main']['App']['ScanNormal']();
}

export function ScanNormalPath(arg1) {
  return window['go']['main']['App']['ScanNormalPath'](arg1);
}

export function SetCategoryEnabled(arg1, arg2) {
  return window['go']['main']['App']['SetCategoryEnabled'](arg1, arg2);
}

export function SetPermanentDelete(arg1) {
  return window['go']['main']['App']['SetPermanentDelete'](arg1);
}
