// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {updater} from '../models';
import {scanner} from '../models';
import {cache} from '../models';
import {settings} from '../models';
import {main} from '../models';

export function CancelClean():Promise<void>;

export function CancelScan():Promise<void>;

export function CheckForUpdate():Promise<updater.UpdateInfo>;

export function CleanCategories(arg1:Array<string>):Promise<scanner.CleanResult>;

export function ClearCache():Promise<void>;

export function ClearTrendsHistory():Promise<void>;

export function DeleteDuplicateGroup(arg1:scanner.DuplicateGroup,arg2:number):Promise<scanner.CleanResult>;

export function DeleteNodeModules(arg1:Array<string>):Promise<scanner.CleanResult>;

export function DeletePath(arg1:string,arg2:boolean):Promise<scanner.CleanResult>;

export function DeletePaths(arg1:Array<string>,arg2:boolean):Promise<scanner.CleanResult>;

export function DownloadUpdate(arg1:string):Promise<string>;

export function FindDuplicates():Promise<scanner.DuplicatesResult>;

export function FindDuplicatesInPath(arg1:string,arg2:number):Promise<scanner.DuplicatesResult>;

export function FindLargeFiles(arg1:number):Promise<scanner.LargeFilesResult>;

export function FindLargeFilesWithOptions(arg1:string,arg2:number,arg3:number,arg4:Array<string>):Promise<scanner.LargeFilesResult>;

export function FormatSize(arg1:number):Promise<string>;

export function GetCacheInfo():Promise<cache.CacheInfo>;

export function GetCategoryItems(arg1:string):Promise<Array<scanner.FileNode>>;

export function GetDevCategories():Promise<Array<scanner.Category>>;

export function GetDirectoryChildren(arg1:string):Promise<Array<scanner.FileNode>>;

export function GetDiskTrends():Promise<scanner.TrendsResult>;

export function GetGrowthAlerts(arg1:number):Promise<Array<scanner.DiskUsageTrend>>;

export function GetHomeDir():Promise<string>;

export function GetPermanentDelete():Promise<boolean>;

export function GetSettings():Promise<settings.Settings>;

export function GetVersion():Promise<main.VersionInfo>;

export function InstallUpdate(arg1:string):Promise<void>;

export function IsCategoryEnabled(arg1:string):Promise<boolean>;

export function LoadCachedDevScan():Promise<cache.CachedDevScan>;

export function LoadCachedNormalScan():Promise<cache.CachedNormalScan>;

export function OpenReleasePage(arg1:string):Promise<void>;

export function QuickScanDev():Promise<scanner.ScanResult>;

export function RecordDiskSnapshot(arg1:scanner.ScanResult):Promise<void>;

export function SaveSettings(arg1:settings.Settings):Promise<void>;

export function ScanCategory(arg1:string):Promise<scanner.Category>;

export function ScanDev():Promise<scanner.ScanResult>;

export function ScanNodeModules():Promise<scanner.NodeModulesResult>;

export function ScanNormal():Promise<scanner.FullScanResult>;

export function ScanNormalPath(arg1:string):Promise<scanner.FullScanResult>;

export function SetCategoryEnabled(arg1:string,arg2:boolean):Promise<void>;

export function SetPermanentDelete(arg1:boolean):Promise<void>;

export function SetCompactMode():Promise<void>;

export function SetFullMode():Promise<void>;

export function IsCompactMode():Promise<boolean>;

export function GetRecommendations():Promise<scanner.RecommendationsResult>;

export function GetQuickRecommendations():Promise<scanner.Recommendation[]>;
